name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: npm ci
      - name: Git Setup
        run: |
          git --version
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Bump version and publish
        id: version
        run: |
          npm version patch
          echo ::set-output name=version::$(node -p "require('./package.json').version")
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Bump version to ${{ steps.version.outputs.version }}"
          git push
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
